sonar.projectKey=FreeYourSoul_FiL
sonar.organization=freeyoursoul

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=FiL

sonar.sources=include,internal/src,internal/p2p
sonar.tests=tests

sonar.cpp.file.suffixes=.hh,.cpp,.hpp
sonar.cfamily.compile-commands=compile_commands.json
sonar.cfamily.cobertura.reportPaths=result/coverage/cobertura.xml

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8